// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Del(arg1, arg2) {
  return window['go']['main']['App']['Del'](arg1, arg2);
}

export function Entries(arg1) {
  return window['go']['main']['App']['Entries'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Put(arg1, arg2, arg3) {
  return window['go']['main']['App']['Put'](arg1, arg2, arg3);
}
