// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBucket(arg1:string):Promise<string>;

export function Buckets():Promise<string>;

export function Del(arg1:string):Promise<string>;

export function Entries(arg1:string):Promise<string>;

export function ID():Promise<string>;

export function Put(arg1:string):Promise<string>;

export function RemoveBucket(arg1:string):Promise<void>;

export function Root(arg1:string):Promise<string>;

export function ShareBucket(arg1:string):Promise<string>;
