// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Del(arg1:string,arg2:string):Promise<void>;

export function Entries(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Put(arg1:string,arg2:string,arg3:string):Promise<void>;
