// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBucket(arg1) {
  return window['go']['main']['App']['AddBucket'](arg1);
}

export function Buckets() {
  return window['go']['main']['App']['Buckets']();
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function Entries(arg1) {
  return window['go']['main']['App']['Entries'](arg1);
}

export function ID() {
  return window['go']['main']['App']['ID']();
}

export function Put(arg1) {
  return window['go']['main']['App']['Put'](arg1);
}

export function RemoveBucket(arg1) {
  return window['go']['main']['App']['RemoveBucket'](arg1);
}

export function Root(arg1) {
  return window['go']['main']['App']['Root'](arg1);
}
